CREATE DATABASE IF NOT EXISTS mte CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE mte;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    name VARCHAR(255),
    password VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL UNIQUE,
    role VARCHAR(50) NOT NULL DEFAULT 'USER'
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'mte_user'@'%' IDENTIFIED BY 'mte_password';
GRANT ALL PRIVILEGES ON mte.* TO 'mte_user'@'%';
FLUSH PRIVILEGES;