spring:
  datasource:
    url: jdbc:mariadb://db:3306/mte
    username: mte_user
    password: mte_password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true

jwt:
  secret: your-256-bit-secret
  expiration: 86400000

tmdb:
  api-key: ${TMDB_API_KEY}
  base-url: https://api.themoviedb.org/3
  image-base-url: https://image.tmdb.org/t/p/

server:
  port: 8080
  servlet:
    context-path: / 