spring:
  datasource:
    url: jdbc:mariadb://db:3306/moviedb
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

tmdb:
  api:
    key: 3171cfb2f41cc3f3b1642c3460c0a0d0
    base-url: https://api.themoviedb.org/3

server:
  port: 8080
  servlet:
    context-path: / 